# Generated by Django 5.0.1 on 2024-01-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('page_count', models.CharField(max_length=16)),
                ('cover_img_url', models.CharField(max_length=64)),
                ('download_page', models.CharField(max_length=64)),
            ],
        ),
    ]
