# Generated by Django 5.0.1 on 2024-01-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'template'), (2, 'beijing'), (2, 'tubiao')])),
                ('category', models.CharField(max_length=64)),
                ('page_count', models.CharField(max_length=16)),
                ('cover_img_url', models.CharField(max_length=64, null=True)),
                ('download_url', models.CharField(max_length=64)),
            ],
        ),
    ]
