# Generated by Django 5.0.1 on 2024-01-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_alter_pptinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptinfo',
            name='download_url',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
