# Generated by Django 5.0.1 on 2024-01-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0003_alter_pptinfo_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptinfo',
            name='cover_img_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pptinfo',
            name='type',
            field=models.IntegerField(choices=[(1, '模板'), (2, '背景'), (2, '图表')]),
        ),
    ]
